version: 7
preset: laravel
tab-width: 4
use-tabs: false
disabled:
  - no_unused_imports
finder:
  name:
    - "*.php"
  not-name:
    - "*.blade.php"
    - index.php
    - server.php



#php:
#  preset: laravel
#  disabled:
#    - no_unused_imports
#  finder:
#    not-name:
#      - index.php
#      - server.php
#js:
#  finder:
#    not-name:
#      - webpack.mix.js
#css: true
