language: php

php:
  - 7.4

branches:
  only:
    - master

sudo: false

env:
  - APP_DEBUG=false

before_script:
  - composer self-update

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

script: phpunit -c ./phpunit.xml ./tests --coverage-text

notifications:
  webhooks: https://www.lovelion.me/api/hook/travis-ci

addons:
  hosts:
    - www.lovelion.me
